# print('puttina roju jejelu chitti vamsi neeku eteta ilage pandaga jaragali puttina roju jejelu chitti vamsi kala kala laade nee kallu devudi illamma kila kila navve nee momu muddula mootamma kala kala laade nee kallu devudi illamma kila kila navve nee momu muddula mootamma nee kosame ne jeevinchali neevey perigi naa aasalu theerchali')
# x="python is a programming language ."
# vowel=0
# consonants=0
# special_characters=0
# space=0
# for i in x:
#     if i in "AEIOaeiou": #if  i.isalpha():
#         vowel +=1
#     elif i in"@#$%.&*()":
#         special_characters +=1
#     elif i in " ":
#         space +=1
#     else:
#         consonants +=1
# print(vowel,special_characters,space,consonants)
# x=input("enter a string:")
# num=""
# for i in x:
#     if i not in num:
#         num +=i
# print(num)
# seen=set(x)
# print(seen)
# x=input("enter a string:")
# rev=""
# for i in x:
#     rev =i +rev
# print(rev)
# if x==rev:
#     print("palindrome")
# else:
#     print("not palindrome")
# x=input("enter a string:")
# y=input("enter a string:")
# if len(x)==len(y):
#     for i in x:
#         if i in y:
#             continue
#         else:
#             print("not anagram")
#             break
       
# else:
#     print("not anagram")
# def fibonacci(n):
#     if n<=1:
#         return n
#     return fibonacci(n-1) +fibonacci(n-2)
# for i in range(10):
#     print(fibonacci(i),end=" ")
